---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: install webserver on ubuntu
    apt:
      name: apache2
      state: present
    notify: start webserver

  - name: i want to copy index file to all nodes
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: restart webserver

  handlers:
  - name: start webserver
    service:
      name: apache2
      state: started

  - name: restart the webserver
    service:
       name: apache2
       state: restated
   
